# Generated by Django 2.2 on 2019-09-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(default='image/restoran/default.png', null=True, upload_to='image/restoran/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'порция'), (2, 'штук'), (3, 'литр'), (4, 'стакан')])),
                ('unit', models.SmallIntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('image', models.ImageField(default='image/restoran/default.png', null=True, upload_to='image/restoran/')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(default='image/restoran/default.png', null=True, upload_to='image/restoran/')),
                ('tables', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True)),
                ('color', models.SmallIntegerField(blank=True, choices=[(1, 'Green'), (2, 'Yellow'), (3, 'Red'), (4, 'Red Yellow'), (5, 'Blue')], default=1)),
                ('restoran', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.Restoran')),
            ],
        ),
        migrations.CreateModel(
            name='TableProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Жасалуда'), (2, 'Дайын')], default=1)),
                ('unit', models.SmallIntegerField(blank=True)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.Product')),
                ('table', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.Table')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/restoran/default.png', null=True, upload_to='image/restoran/')),
                ('product_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='restoran',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client_app.Restoran'),
        ),
    ]
